name: main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3
        target: esp32
        path: 'examples/hello_world'

    - name: store artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hello_world.bin
        path: |
          examples/hello_world/build/hello_world.bin
        retention-days: 5

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run all tests
        run: |
          pytest tests -v
