name: test

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: run smoke test
        run: |
          chmod +x ./scripts/smoke_test.sh
          ./scripts/smoke_test.sh

      - name: build Docker image and run tests
        run: |
          docker build -t flask-app .
          docker run --rm flask-app pytest -v
