name: test

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: build Docker image and run tests
        run: |
          docker build -t flask-app .
          docker run --rm flask-app pytest -v
